<a href="https://colab.research.google.com/github/naulla/PM-TuRi2-Prepocessing-NaulaAlfiyatulFauziyyah/blob/main/PM-TuRi2-preprocessing-NaulaAlfiyatulFauziyyah.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**C. Langkah Praktikum**

In [44]:
import pandas as pd
import numpy as np

# Dataset karyawan (sengaja mengandung masalah kualitas)
data = {
    'usia'      : [25, 32, np.nan, 45, 28, 51, 38, np.nan, 29, 41],
    'pendapatan': [4_000_000, 7_500_000, 5_200_000, 12_000_000, 4_800_000,
                   15_000_000, 8_100_000, 6_300_000, np.nan, 9_900_000],
    'pendidikan': ['SMA','S1','SMA','S2','SMA','S2','S1','S1','SMA','S2'],  # ordinal
    'kota'      : ['Bandung','Jakarta','Bandung','Surabaya','Jakarta',
                   'Surabaya','Jakarta','Bandung','Bandung','Jakarta'],    # nominal
    'membeli'   : ['Tidak','Ya','Tidak','Ya','Tidak','Ya','Ya','Tidak','Tidak','Ya']  # target
}
df = pd.DataFrame(data)
df

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2   NaN   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7   NaN   6300000.0         S1   Bandung   Tidak
8  29.0         NaN        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

In [55]:
df['usia'] = df['usia'].fillna(df['usia'].median())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].median())
df

,usia,pendapatan,pendidikan,kota,membeli,status_pernikahan_Belum Menikah,status_pernikahan_Menikah
0,25.0,4000000.0,SMA,Bandung,Tidak,1,0
1,32.0,7500000.0,S1,Jakarta,Ya,0,1
2,35.0,5200000.0,SMA,Bandung,Tidak,1,0
3,45.0,12000000.0,S2,Surabaya,Ya,0,1
4,28.0,4800000.0,SMA,Jakarta,Tidak,1,0
5,51.0,15000000.0,S2,Surabaya,Ya,0,1
6,38.0,8100000.0,S1,Jakarta,Ya,0,1
7,35.0,6300000.0,S1,Bandung,Tidak,1,0
8,29.0,7500000.0,SMA,Bandung,Tidak,1,0
9,41.0,9900000.0,S2,Jakarta,Ya,0,1

In [47]:
X = df.drop(columns=['membeli'])
y = df['membeli']
print(X)
print(y)

   usia  pendapatan pendidikan      kota
0  25.0   4000000.0        SMA   Bandung
1  32.0   7500000.0         S1   Jakarta
2  35.0   5200000.0        SMA   Bandung
3  45.0  12000000.0         S2  Surabaya
4  28.0   4800000.0        SMA   Jakarta
5  51.0  15000000.0         S2  Surabaya
6  38.0   8100000.0         S1   Jakarta
7  35.0   6300000.0         S1   Bandung
8  29.0   7500000.0        SMA   Bandung
9  41.0   9900000.0         S2   Jakarta
0    Tidak
1       Ya
2    Tidak
3       Ya
4    Tidak
5       Ya
6       Ya
7    Tidak
8    Tidak
9       Ya
Name: membeli, dtype: object

In [48]:
X['pendidikan'] = X['pendidikan'].map({'SMA':0,'S1':1,'S2':2}) # ordinal
X = pd.get_dummies(X, columns=['kota'], dtype=int) # nominal
y = y.map({'Tidak':0,'Ya':1})
print(X)
print(y)

   usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0  25.0   4000000.0           0             1             0              0
1  32.0   7500000.0           1             0             1              0
2  35.0   5200000.0           0             1             0              0
3  45.0  12000000.0           2             0             0              1
4  28.0   4800000.0           0             0             1              0
5  51.0  15000000.0           2             0             0              1
6  38.0   8100000.0           1             0             1              0
7  35.0   6300000.0           1             1             0              0
8  29.0   7500000.0           0             1             0              0
9  41.0   9900000.0           2             0             1              0
0    0
1    1
2    0
3    1
4    0
5    1
6    1
7    0
8    0
9    1
Name: membeli, dtype: int64

In [52]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
X, y, test_size=0.3, random_state=42)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

   usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0  25.0   4000000.0           0             1             0              0
7  35.0   6300000.0           1             1             0              0
2  35.0   5200000.0           0             1             0              0
9  41.0   9900000.0           2             0             1              0
4  28.0   4800000.0           0             0             1              0
3  45.0  12000000.0           2             0             0              1
6  38.0   8100000.0           1             0             1              0
0    0
7    0
2    0
9    1
4    0
3    1
6    1
Name: membeli, dtype: int64
   usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
8  29.0   7500000.0           0             1             0              0
1  32.0   7500000.0           1             0             1              0
5  51.0  15000000.0           2             0             0              1
8    0
1    1
5    1
Name: membeli, dtype: int64

In [57]:
from sklearn.preprocessing import StandardScaler
num = ['usia','pendapatan','pendidikan']
sc = StandardScaler()
X_train[num] = sc.fit_transform(X_train[num])
X_test[num] = sc.transform(X_test[num]) # cegah data leakage

**D. Latihan Mandiri**
1. Ganti imputasi usia menjadi mean; bandingkan hasilnya.

Jawaban: Berdasarkan hasil perhitungan nilai mean usia adalah 36,125, sedangkan nilai mediannya adalah 35. Setelah menggunakan mean, nilai NaN pada kolomusia diganti dengan 36,125, dan jika menggunakan median nilai NaN akan diganti dengan 35.

In [58]:
df['usia'] = df['usia'].fillna(df['usia'].mean())
df

,usia,pendapatan,pendidikan,kota,membeli,status_pernikahan_Belum Menikah,status_pernikahan_Menikah
0,25.0,4000000.0,SMA,Bandung,Tidak,1,0
1,32.0,7500000.0,S1,Jakarta,Ya,0,1
2,35.0,5200000.0,SMA,Bandung,Tidak,1,0
3,45.0,12000000.0,S2,Surabaya,Ya,0,1
4,28.0,4800000.0,SMA,Jakarta,Tidak,1,0
5,51.0,15000000.0,S2,Surabaya,Ya,0,1
6,38.0,8100000.0,S1,Jakarta,Ya,0,1
7,35.0,6300000.0,S1,Bandung,Tidak,1,0
8,29.0,7500000.0,SMA,Bandung,Tidak,1,0
9,41.0,9900000.0,S2,Jakarta,Ya,0,1

2. Gunakan MinMaxScaler (0–1) sebagai ganti StandardScaler; tampilkan describe().

Jawaban: Hasil describenya menunjukkan statistik data setelah dilakukan MinMaxScaler. Jadi nilai minimum pada data latih menjadi diubah menjadi 0  dan nilai maksimum menjadi 1.

In [50]:
from sklearn.preprocessing import MinMaxScaler
num = ['usia','pendapatan','pendidikan']
mms = MinMaxScaler()
X_train[num] = mms.fit_transform(X_train[num])
X_test[num] = mms.transform(X_test[num]) # cegah data leakage
print(X_train[num].describe())

           usia  pendapatan  pendidikan
count  7.000000    7.000000    7.000000
mean   0.530357    0.398214    0.428571
std    0.349971    0.367808    0.449868
min    0.000000    0.000000    0.000000
25%    0.353125    0.125000    0.000000
50%    0.556250    0.287500    0.500000
75%    0.725000    0.625000    0.750000
max    1.000000    1.000000    1.000000

3. Tambahkan kolom kategorikal baru dan terapkan one-hot encoding.

In [51]:
df['status_pernikahan'] = [
    'Belum Menikah', 'Menikah', 'Belum Menikah', 'Menikah',
    'Belum Menikah', 'Menikah', 'Menikah', 'Belum Menikah',
    'Belum Menikah', 'Menikah'
]
df = pd.get_dummies(df, columns=['status_pernikahan'], dtype=int)
df

,usia,pendapatan,pendidikan,kota,membeli,status_pernikahan_Belum Menikah,status_pernikahan_Menikah
0,25.0,4000000.0,SMA,Bandung,Tidak,1,0
1,32.0,7500000.0,S1,Jakarta,Ya,0,1
2,35.0,5200000.0,SMA,Bandung,Tidak,1,0
3,45.0,12000000.0,S2,Surabaya,Ya,0,1
4,28.0,4800000.0,SMA,Jakarta,Tidak,1,0
5,51.0,15000000.0,S2,Surabaya,Ya,0,1
6,38.0,8100000.0,S1,Jakarta,Ya,0,1
7,35.0,6300000.0,S1,Bandung,Tidak,1,0
8,29.0,7500000.0,SMA,Bandung,Tidak,1,0
9,41.0,9900000.0,S2,Jakarta,Ya,0,1

4. Jelaskan mengapa fit_transform pada latih tetapi hanya transform pada uji.

Jawaban: fit_transform digunakan pada data latih karena scaler perlu mempelajari nilai dari data latih terlebih dahulu. Sedangkan data uji hanya menggunakan transform, agar menggunakan hasil perhitungan dari data latih. Jika data uji menggunakan fit_transorm, bisa terjadi data leakage karena scaler ikut mempelajari data uji.

**E. Refleksi**
1. Mengapa urutan 'split dulu, baru scaling' penting?

Jawaban: Karena jika tidak di spit terlebih dahulu maka akan ada kebocoran informasi yaitu data uji saat pelatihan. Informasi dari data uji ini akan memengaruhi hasil scaling sehingga hasil pengujian model menjadi kurang objektif.

2. Kapan label encoding dan kapan one-hot encoding?

Jawaban: Label encoding digunakan untuk data yang memiliki urutan/ordinal dan hasilnya berupa satu kolom angka. Sedangkan one-hot encoding digunakan untuk data yang tidak memiliki urutan/nominal dan hasilnya berupa beberapa kolom dengan nilai 0 ataupun 1.  

3. Apa perbedaan normalisasi dan standardisasi?

Jawaban: Perbedaannya terletak pada hasil skala datanya. Normalisasi adalah proses mengubah skala data ke rentang tetap dan berguna ketika data membutuhkan batasan nilai yang jelas, tetapi normalisasi sensitif terhadap outlier. Sedangkan standardisasi adalah proses mengubah data sehingga memiliki mean/rata-rata 0 dan standar deviasi 1 dan hasilnya tidak memiliki batas rentang tertentu dan lebih tahan terhadap outlier.